var gvjs_FU="Must drawMap before enabling pointer sensitivity.",gvjs_GU="google-visualization-intensitymap-tab";function gvjs_HU(){gvjs_in.call(this);this.eP=[];this.be=[]}gvjs_q(gvjs_HU,gvjs_in);gvjs_=gvjs_HU.prototype;gvjs_.JD=gvjs_ea;gvjs_.rT="#f0f0f0";gvjs_.$ma="#eaf7fe";gvjs_.vp=440;gvjs_.tv=220;var gvjs_IU={NEa:gvjs_sy,UBa:"africa",ZBa:"asia",JCa:"europe",wDa:"middle_east",kEa:"south_america",IEa:"usa"};gvjs_HU.prototype.O2=null;gvjs_HU.prototype.qK=gvjs_sy;gvjs_HU.prototype.O7=null;
var gvjs_JU={};gvjs_=gvjs_HU.prototype;gvjs_.L8=function(a,b,c){var d={};d.text=a;d.color=gvjs_Tc(b).gc;d.zH=c;this.be.push(d)};gvjs_.Zya=function(a){this.be=a};gvjs_.getColors=function(){if(this.be){for(var a=[],b=0;b<this.be.length;b++)a.push(this.be[b].color);return a}return null};gvjs_.getData=function(a){if(this.be&&0<this.be.length){for(var b=[],c=-1,d=0;-1==c&&d<this.eP.length;d++)this.eP[d]==a&&(c=d);for(d=0;-1!=c&&d<this.be.length;d++)b.push(this.be[d].zH[c]);return b}return null};
gvjs_.Jha=function(a){this.eP=a};gvjs_.cza=function(a){this.JD=gvjs_Tc(a).gc};gvjs_.dza=function(a){this.rT=gvjs_Tc(a).gc};gvjs_.sf=function(a,b){this.vp=a;this.tv=b};gvjs_.Pha=function(a){this.qK=a};gvjs_.getContainer=function(){return this.ea};
gvjs_.zaa=function(a,b,c){this.ea=gvjs_fm().j(a);a=new gvjs_dL("t");gvjs_iL(a,[this.qK]);a.wI="e";gvjs_fL(a).pd("chf","bg,s,"+this.$ma.substr(1));a.sf(this.vp,this.tv);var d=this.eP.join(""),e=this.be[b].zH;if(gvjs_i(c)){for(var f=this.be[c].zH,g=[],h=0;h<e.length;h++){var k=e[h],l=f[h];if(null!=k||null!=l)k=gvjs_i(k)?k:0,l=gvjs_i(l)?l:0,g[h]=l-k}var f=e=g,g=[0,0],h=gvjs_KU(f),l=h[0],m=h[1],h=Math.abs(l),k=Math.abs(m),l=0>l,m=0<m;if(l&&m)for(g=[1,1],(l=k>h)?(h=k/h,g[0]=h):(h/=k,g[1]=h),k=0;k<f.length;k++){if(l&&
0>f[k]||!l&&0<f[k])f[k]*=h}else l||m?l?g[0]=Math.max(1-k/h,.01):g[1]=Math.max(1-h/k,.01):g=[0,0];f=g[0];g=g[1];b=this.be[b].color;c=this.be[c].color;h=this.JD;k=[];0==f?(k[0]=gvjs_LU(h,c,g),k[1]=c):0==g?(k[0]=b,k[1]=gvjs_LU(h,b,f)):(k[0]=gvjs_LU(h,b,1-1/f),k[1]=h,k[2]=gvjs_LU(h,c,1-1/g));b=k}else b=[this.JD.substr(1),this.be[b].color];c=null;try{gvjs_pL(a,e,this.rT.substr(1)+","+b.join(",").replace(/#/g,"")),gvjs_fL(a).pd("chld",d)}catch(n){c=gvjs_fL(a),c.pd("chd","e:__")}d=this.ea.style;d.width=
this.vp+gvjs_M;d.height=this.tv+gvjs_M;null==c&&(c=gvjs_fL(a));c.sm||gvjs_Dn(c,gvjs_Vi);this.O2=c;d.background='url("'+this.O2+'") no-repeat top left'};function gvjs_LU(a,b,c){return gvjs_Xc(gvjs_4c(gvjs_Zc(a),gvjs_Zc(b),c))}
gvjs_.xaa=function(a,b,c,d,e,f){var g=null!=f,h,k=null,l=null;if(null==d||null==e)h=gvjs_KU(this.be[b].zH),g&&(k=gvjs_KU(this.be[f].zH)),g&&(l=Math.max(k[0],k[1])),null!=d||(d=g?k[1]:h[0]),null!=e||(e=h[1]);h=gvjs_fm();a=h.j(a);h.pc(a);var k=h.H(gvjs_Ia,{align:gvjs_1,height:gvjs_$q}),m;b=this.be[b].color;m=g?this.be[f].color:this.JD;d!=e||g||(b=m=this.rT);var n=String(d).length+String(e).length;f=12;n*f*.75>this.vp&&(f=this.vp-0*c-4-c,f=Math.ceil(f/n/.75));for(var n=Math.ceil((this.vp-n*f*.75-0*c-
4)/c),p=0;p<c;p++)if(g)if(p<Math.floor(c/2))k.appendChild(h.H(gvjs_Ga,{width:n+gvjs_M,style:gvjs_Sa+gvjs_LU(this.JD,m,p/Math.floor(c/2))}));else{var q=p==Math.floor(c/2)?"0":null;k.appendChild(h.H(gvjs_Ga,{width:n+gvjs_M,style:gvjs_Sa+gvjs_LU(b,this.JD,(p-Math.floor(c/2))/Math.floor(c/2))},q))}else k.appendChild(h.H(gvjs_Ga,{width:n+gvjs_M,style:gvjs_Sa+gvjs_LU(b,m,p/c)}));c=h.H(gvjs_Ea,{cellpadding:"0",cellspacing:"0"},h.H(gvjs_Fa,null,k));d=h.H(gvjs_Ea,{cellpadding:"0",cellspacing:"2"},h.H(gvjs_Fa,
null,h.H(gvjs_Ia,null,h.H(gvjs_Ga,{style:"text-align: right; font-size: "+f+"px;"},String(Math.round(100*(l?l:d))/100)),h.H(gvjs_Ga,null,c),h.H(gvjs_Ga,{style:"text-align: left; font-size: "+f+"px;"},String(Math.round(100*(l?l:e))/100)))));h.appendChild(a,d)};var gvjs_MU={},gvjs_NU={};gvjs_HU.prototype.Gd=null;
gvjs_HU.prototype.Jaa=function(a){var b=this.qK+"_"+this.vp+"x"+this.tv;if(!this.ea)throw Error(gvjs_FU);this.ea.style.position=gvjs_yi;a&&gvjs_4ia(this);gvjs_JU[b]?(this.O7=gvjs_JU[b],gvjs_5ia(this)):(gvjs_MU[b]||(gvjs_MU[b]=[]),gvjs_MU[b].push({instance:this,container:this.ea}),gvjs_NU[b]||(gvjs_NU[b]=function(a){gvjs_JU[b]=a.chartshape;a=gvjs_MU[b];for(var c=0;c<a.length;c++)a[c].FFa.Jaa(a[c].ga);gvjs_MU[b]=null;gvjs_NU[b]=null}),gvjs_6ia(this,"HeatMap.heatmapCallback."+b))};
function gvjs_4ia(a){if(!a.Gd){var b=gvjs_1f(a.ea),c=a.vp,d=a.tv,e=a.vp,f=a.tv,c=!gvjs_A||gvjs_Wf("9")&&gvjs_1f().zc().createElementNS?!gvjs_Kf||gvjs_Wf("420")&&!gvjs_Lf?new gvjs_xO(c,d,e,f,void 0):new gvjs_lO(c,d,e,f,void 0):new gvjs_MO(c,d,e,f,void 0);c.H();a.Gd=c;b=b.H(gvjs_a,{style:"left: 0; top: 0; z-index: 0; position: absolute"});a.Gd.W(b);a.ea.appendChild(b)}}gvjs_HU.prototype.Lba=function(){return this.Gd};
function gvjs_5ia(a){if(!a.ea)throw Error(gvjs_FU);for(var b=gvjs_1f(a.ea),c=a.ea.id+"_vectorMap",d=b.H("IMG",{src:a.O2.toString(),width:a.vp,height:a.tv,border:"0",usemap:"#"+c,style:"left: 0; top: 0; z-index: 1; opacity: 0; position: absolute"}),c=b.H(gvjs_Pr,{name:c}),e=0;e<a.O7.length;e++){var f=a.O7[e],f=b.H("AREA",{id:a.ea.id+"_"+f.name,shape:f.type,coords:f.coords},"");c.appendChild(f)}gvjs_W(c,[gvjs_Yj,gvjs_Gi,gvjs_Hi,gvjs_7v],function(b){a.As(a,b)});a.ea.appendChild(d);a.ea.appendChild(c)}
gvjs_HU.prototype.As=function(a,b){return this.dispatchEvent(b)};function gvjs_OU(a){a=a.target.id;return a.substr(a.lastIndexOf("_")+1)}function gvjs_6ia(a,b){var c=new gvjs_dL("t");gvjs_iL(c,[a.qK]);c.sf(a.vp,a.tv);gvjs_pL(c,[0,1],a.rT.substring(1));a=gvjs_fL(c);a.pd("chof","json");a.pd("callback",b);a.sm||gvjs_Dn(a,gvjs_Vi);b=a.toString();gvjs_gm().write(gvjs_Ek+b+'">\x3c/script>')}
function gvjs_KU(a){for(var b=null,c=null,d,e=0;e<a.length;e++)if(d=a[e],gvjs_i(d)){if(null==b||d>b)b=d;if(null==c||d<c)c=d}return[c,b]}gvjs_j("HeatMap",gvjs_HU,void 0);gvjs_j("HeatMap.MapRegion",gvjs_IU,void 0);gvjs_HU.prototype.drawMap=gvjs_HU.prototype.zaa;gvjs_HU.prototype.drawGradient=gvjs_HU.prototype.xaa;gvjs_HU.prototype.enablePointerSensitivity=gvjs_HU.prototype.Jaa;gvjs_HU.prototype.setCountriesIds=gvjs_HU.prototype.Jha;gvjs_HU.prototype.addDataset=gvjs_HU.prototype.L8;
gvjs_HU.prototype.setDatasets=gvjs_HU.prototype.Zya;gvjs_HU.prototype.setMapRegion=gvjs_HU.prototype.Pha;gvjs_HU.prototype.setNoValueColor=gvjs_HU.prototype.dza;gvjs_HU.prototype.setNeutralColor=gvjs_HU.prototype.cza;gvjs_HU.prototype.getGraphics=gvjs_HU.prototype.Lba;gvjs_j("HeatMap.heatmapCallback",gvjs_NU,void 0);var gvjs_7ia={AD:"Andorra",AE:"United Arab Emirates",AF:"Afghanistan",AG:"Antigua and Barbuda",AI:"Anguilla",AL:"Albania",AM:"Armenia",AN:"Netherlands Antilles",AO:"Angola",AR:"Argentina",AS:"American Samoa",AT:"Austria",AU:"Australia",AW:"Aruba",AZ:"Azerbaijan",BA:"Bosnia and Herzegovina",BB:"Barbados",BD:"Bangladesh",BE:"Belgium",BF:"Burkina Faso",BG:"Bulgaria",BH:"Bahrain",BI:"Burundi",BJ:"Benin",BM:"Bermuda",BN:"Brunei Darussalam",BO:"Bolivia",BR:"Brazil",BS:"Bahamas",BT:"Bhutan",BW:"Botswana",
BY:"Belarus",BZ:"Belize",CA:"Canada",CD:"Congo, Democratic Republic",CF:"Central African Republic",CG:"Congo",CH:"Switzerland",CI:"Cote d'Ivoire",CK:"Cook Islands",CL:"Chile",CM:"Cameroon",CN:"China",CO:"Colombia",CR:"Costa Rica",CU:"Cuba",CV:"Cape Verde",CY:"Cyprus",CZ:"Czech Republic",DE:"Germany",DJ:"Djibouti",DK:"Denmark",DM:"Dominica",DO:"Dominican Republic",DZ:"Algeria",EC:"Ecuador",EE:"Estonia",EG:"Egypt",ER:"Eritrea",ES:"Spain",ET:"Ethiopia",FI:"Finland",FJ:"Fiji",FM:"Micronesia",FO:"Faroe Islands",
FR:"France",GA:"Gabon",GB:"United Kingdom",GD:"Grenada",GE:"Georgia",GF:"French Guiana",GH:"Ghana",GI:"Gibraltar",GL:"Greenland",GM:"Gambia",GN:"Guinea",GP:"Guadeloupe",GR:"Greece",GT:"Guatemala",GU:"Guam",GY:"Guyana",HK:"Hong Kong",HN:"Honduras",HR:"Croatia",HT:"Haiti",HU:"Hungary",ID:"Indonesia",IE:"Ireland",IL:"Israel",IN:"India",IQ:"Iraq",IR:"Iran",IS:"Iceland",IT:"Italy",JM:"Jamaica",JO:"Jordan",JP:"Japan",KE:"Kenya",KG:"Kyrgyzstan",KH:"Cambodia",KN:"Saint Kitts and Nevis",KP:"North Korea",KR:"South Korea",
KW:"Kuwait",KY:"Cayman Islands",KZ:"Kazakhstan",LA:"Lao People's Democratic Republic",LB:"Lebanon",LC:"Saint Lucia",LI:"Liechtenstein",LK:"Sri Lanka",LS:"Lesotho",LT:"Lithuania",LU:"Luxembourg",LV:"Latvia",LY:"Libya",MA:"Morocco",MC:"Monaco",MD:"Moldova",MG:"Madagascar",MK:"Macedonia",ML:"Mali",MM:"Myanmar",MN:"Mongolia",MO:"Macau",MP:"Northern Mariana Islands",MQ:"Martinique",MR:"Mauritania",MT:"Malta",MU:"Mauritius",MV:"Maldives",MW:"Malawi",MX:"Mexico",MY:"Malaysia",MZ:"Mozambique",NA:"Namibia",
NC:"New Caledonia",NE:"Niger",NG:"Nigeria",NI:"Nicaragua",NL:"Netherlands",NO:"Norway",NP:"Nepal",NZ:"New Zealand",OM:"Oman",PA:"Panama",PE:"Peru",PF:"French Polynesia",PG:"Papua New Guinea",PH:"Philippines",PK:"Pakistan",PL:"Poland",PR:"Puerto Rico",PS:"Palestinian Territory",PT:"Portugal",PW:"Palau",PY:"Paraguay",QA:"Qatar",RO:"Romania",RU:"Russian Federation",RW:"Rwanda",SA:"Saudi Arabia",SB:"Solomon Islands",SC:"Seychelles",SD:"Sudan",SE:"Sweden",SG:"Singapore",SH:"St. Helena",SI:"Slovenia",SK:"Slovakia",
SL:"Sierra Leone",SM:"San Marino",SN:"Senegal",SO:"Somalia",SR:"Suriname",SV:"El Salvador",SY:"Syria",SZ:"Swaziland",TC:"Turks and Caicos Islands",TD:"Chad",TG:"Togo",TH:"Thailand",TJ:"Tajikistan",TL:"East Timor",TM:"Turkmenistan",TN:"Tunisia",TO:"Tonga",TR:"Turkey",TT:"Trinidad and Tobago",TW:"Taiwan",TZ:"Tanzania",UA:"Ukraine",UG:"Uganda",US:"United States",UY:"Uruguay",UZ:"Uzbekistan",VA:"Vatican",VC:"Saint Vincent and the Grenadines",VE:"Venezuela",VG:"Virgin Islands (British)",VI:"Virgin Islands (U.S.)",
VN:"Viet Nam",VU:"Vanuatu",WS:"Samoa",YE:"Yemen",YT:"Mayotte",YU:"Yugoslavia",ZA:"South Africa",ZM:"Zambia",ZW:"Zimbabwe"},gvjs_8ia={"US-AL":"Alabama","US-AK":"Alaska","US-AZ":"Arizona","US-AR":"Arkansas","US-CA":"California","US-CO":"Colorado","US-CT":"Connecticut","US-DE":"Delaware","US-DC":"District of Columbia","US-FL":"Florida","US-GA":"Georgia","US-HI":"Hawaii","US-ID":"Idaho","US-IL":"Illinois","US-IN":"Indiana","US-IA":"Iowa","US-KS":"Kansas","US-KY":"Kentucky","US-LA":"Louisiana","US-ME":"Maine",
"US-MD":"Maryland","US-MA":"Massachusetts","US-MI":"Michigan","US-MN":"Minnesota","US-MS":"Mississippi","US-MO":"Missouri","US-MT":"Montana","US-NE":"Nebraska","US-NV":"Nevada","US-NH":"New Hampshire","US-NJ":"New Jersey","US-NM":"New Mexico","US-NY":"New York","US-NC":"North Carolina","US-ND":"North Dakota","US-OH":"Ohio","US-OK":"Oklahoma","US-OR":"Oregon","US-PA":"Pennsylvania","US-RI":"Rhode Island","US-SC":"South Carolina","US-SD":"South Dakota","US-TN":"Tennessee","US-TX":"Texas","US-UT":"Utah",
"US-VT":"Vermont","US-VA":"Virginia","US-WA":"Washington","US-WV":"West Virginia","US-WI":"Wisconsin","US-WY":"Wyoming"};function gvjs_9ia(a,b){return b&&"US"==a.toUpperCase()?gvjs_8ia["US-"+b]:b?"unknown":gvjs_7ia[a]};function gvjs_PU(a,b){this.qa=a instanceof gvjs_w?a:new gvjs_w(a,b)}gvjs_q(gvjs_PU,gvjs_Fy);gvjs_PU.prototype.Jf=function(a,b,c,d){var e;e=gvjs_3f(a);var f=e.body;e=e.documentElement;e=new gvjs_w(f.scrollLeft||e.scrollLeft,f.scrollTop||e.scrollTop);f=this.qa.x+e.x;e=this.qa.y+e.y;var g=gvjs_Iy(a),f=f-g.x;e-=g.y;gvjs_Ky(new gvjs_w(f,e),a,b,c,null,null,d)};function gvjs_QU(a,b,c){this.Ts=a;this.d0=c||gvjs_9ia;this.Gd=a.Gd;this.Gc=null;if(this.Nr=gvjs_fm().j(b||""))this.Nr.style.position=gvjs_O,this.Nr.style.visibility=gvjs_Xi;this.Gd&&(this.L0=this.Gd.Ua(),this.Ee=new gvjs_oO(1,"red"));var d=this;gvjs_W(this.Ts,gvjs_Gi,function(a){var b=a.target.coords,c=gvjs_OU(a);d.Ts.getData(c);d.Nr&&d.nI(a.clientX,a.clientY,c);a=b.split(",");if(d.Gd){b=new gvjs_ZN;b.moveTo(Number(a[0]),Number(a[1]));for(c=2;c<a.length;c+=2)b.lineTo(Number(a[c]),Number(a[c+1]));
b.lineTo(Number(a[0]),Number(a[1]));d.Gd.La(b,d.Ee,null,d.L0)}},!0);gvjs_W(this.Ts,gvjs_Hi,function(){d.Nr&&gvjs_$ia(d);d.L0&&d.L0.clear()},!0);gvjs_W(this.Ts,gvjs_7v,function(a){d.Nr&&d.Gc&&d.Gc.la()&&d.nI(a.clientX,a.clientY)},!0);gvjs_W(this.Ts,gvjs_Yj,function(a){window.console&&window.console.info("clicked on "+gvjs_OU(a))},!0)}gvjs_QU.prototype.setStrokeColor=function(a){this.Ee.color=a};
gvjs_QU.prototype.nI=function(a,b,c){this.Z9=!0;this.Gc||(this.Gc=new gvjs_Ry(this.Nr),this.Gc.gV(!1));if(c){var d=this.Ts.getData(c),e=this.Ts.getColors(),f;f=this.Ts;if(f.be&&0<f.be.length){for(var g=[],h=0;h<f.be.length;h++)g.push(f.be[h].text);f=g}else f=null;g="<div>";g=this.d0?"usa"==this.Ts.qK?g+this.d0("US",c):g+this.d0(c):g+c;g+=gvjs_0;for(c=0;c<d.length;c++)g+='<span style="color:'+e[c]+gvjs_Dq+gvjs_Xb(gvjs_ze(f[c]))+":&nbsp;"+d[c]+"</span><br/>";this.Nr.innerHTML=g;this.N9=gvjs_5k(this.Nr)}this.Gc.setPosition(new gvjs_PU(Math.max(a,
this.N9.width),Math.max(0,b-this.N9.height)));this.Gc.la()||(a=this.Gc,a.sga=4,a.la()&&a.Jf(),this.Gc.setVisible(!0))};function gvjs_$ia(a){a.Z9=!1;a.Gc&&window.setTimeout(function(){a.Z9||a.Gc.setVisible(!1)},100)}gvjs_j("HeatMapInteractive",gvjs_QU,void 0);gvjs_QU.prototype.setStrokeClor=gvjs_QU.prototype.setStrokeColor;function gvjs_RU(a){gvjs_rp.call(this,a);this.G=gvjs_fm();this.M4=gvjs_sy;this.YV=[];this.E6=[];this.t3=[];this.Jb=gvjs_SU;this.GZ=0}gvjs_q(gvjs_RU,gvjs_rp);gvjs_RU.prototype.ha=null;gvjs_RU.prototype.Ma=null;var gvjs_SU=[gvjs_Rq,gvjs_Jq,"#80C65A","#FF0000","#FFCC33","#BBCCED",gvjs_Jq,"#990066"];function gvjs_TU(a,b){a.M4=gvjs_sy;gvjs_i(b)&&gvjs_yd(gvjs_IU,b)&&(a.M4=b)}gvjs_=gvjs_RU.prototype;gvjs_.ME=function(a){this.Jb=a};gvjs_.jC=function(){return this.Jb};gvjs_.getSelection=function(){return[{column:this.GZ}]};
gvjs_.setSelection=function(a){a&&a[0]&&a[0].column&&this.d1(a[0].column-1)};
gvjs_.Hg=function(a,b,c){var d=c||{};a=this.ga;if(!a)throw Error(gvjs_uk);if(!b)throw Error(gvjs_Gr);d.colors?this.ME(d.colors):this.ME(gvjs_SU);d.region?gvjs_TU(this,d.region):gvjs_TU(this,gvjs_sy);c=d.width;var e=d.height,f=!!d.showOneTab,d=this.G,g=null,h=!0,k=b.Y();if(1>=k||b.X(0)!=gvjs_f)h=!1;for(var l=1;h&&l<k;l++)h=b.X(l)==gvjs_e;h||(g=d.H(gvjs_a,{"class":"google-visualization-intensitymap-message"},"The data format is invalid for this visualization. The data should contain 2 or more columns. The first column should contain ISO country codes, and the rest of the columns should contain numeric values."));h=
b.Y();k=[];for(l=0;l<h;l++)k.push(b.Xa(l));l=k.join(",");if(h!=this.J3+1||l!=this.Ema)for(this.J3=0,gvjs_jc(this.t3),gvjs_jc(this.E6),this.Ema=l,this.J3=h-1,gvjs_UU(this,b),b=this.G,l=0;l<this.J3;l++){var m=b.createElement(gvjs_Za);gvjs_Q(m,"overflow",gvjs_3j);var n=b.createElement(gvjs_Za),p=b.createElement(gvjs_Za);p.className="google-visualization-intensitymap-legend";b.appendChild(m,n);b.appendChild(m,p);this.E6.push(m)}else gvjs_UU(this,b);b=d.H(gvjs_Ia,null);for(l=1;l<h;l++)m=d.H(gvjs_Ga,{"class":gvjs_GU},
d.H(gvjs_dk,{"class":"google-visualization-intensitymap-tab-text",style:"color: "+this.jC()[l-1]},k[l])),gvjs_W(m,gvjs_Yj,gvjs_p(this.d1,this,l-1)),d.appendChild(b,m),this.YV[l-1]=m;h=(f=2<h||f)?26:0;k=c?c-2:c;l=e?e-18-h-2:e;if(k||l){k=k?k:2*l;l=l?l:k/2;if(440<k||0>k||220<l||0>l)k=440,l=220;k=new gvjs_z(k,l)}else k=new gvjs_z(440,220);this.ha=k.width;this.Ma=k.height;k=this.ha;l=this.Ma+18;this.M2=d.H(gvjs_a,{"class":"google-visualization-intensitymap-map",style:"width: "+k+"px; height: "+l+"px;"});
d.pc(a);d.qw(a,{"class":"google-visualization-intensitymap-container",style:"width: "+(c||k)+"px; height: "+(e||l+h)+"px;"});c=f?d.H(gvjs_a,null,d.H(gvjs_Ea,{"class":"google-visualization-intensitymap-tab-table",style:"height: 25px;"},d.H(gvjs_Fa,null,b)),this.M2):d.H(gvjs_a,null,this.M2);d.appendChild(a,c);null!=g&&d.appendChild(a,g);this.d1(this.GZ)};
gvjs_.d1=function(a){var b=this.G;this.GZ=a;var c=this.YV[a];this.Jya=a;for(a=0;a<this.YV.length;a++)b.qw(this.YV[a],{"class":gvjs_GU});b.qw(c,{"class":"google-visualization-intensitymap-selected-tab"});gvjs_X(this,gvjs_J,{});b=this.Jya;c=this.E6[b];a=c.childNodes;this.KC.sf(this.ha,this.Ma);this.KC.zaa(a[0],b);this.KC.xaa(a[1],b,10);this.M2.innerHTML=c.innerHTML;gvjs_X(this,gvjs_L,null);this.t3[b]=!1};
function gvjs_UU(a,b){for(var c=b.Y(),d=b.fa(),e=[],f=0;f<d;f++)e.push(b.getValue(f,0));a.KC=new gvjs_HU;a.KC.Pha(a.M4);a.KC.Jha(e);for(e=1;e<c;e++){var g=e-1;a.t3[g]=!0;for(var h=[],f=0;f<d;f++)h.push(b.getValue(f,e));f=a.jC()[g%a.jC().length];a.KC.L8(b.Xa(e),f,h)}};gvjs_j(gvjs_cj,gvjs_RU,void 0);gvjs_RU.prototype.draw=gvjs_RU.prototype.draw;gvjs_RU.prototype.getSelection=gvjs_RU.prototype.getSelection;gvjs_RU.prototype.setSelection=gvjs_RU.prototype.setSelection;
