function gvjs_tY(a){gvjs_rp.call(this,a);this.kd=new gvjs_np(this,this.ga);this.wu="google.visualization.MotionChart-"+gvjs_Nka++;gvjs_uY[this.wu]=this;this.XV=this.wu+"_swf";a.id||(a.id=this.wu);this.tva=gvjs_lm()}gvjs_q(gvjs_tY,gvjs_rp);var gvjs_vY=gvjs_NM("flash_subdir",gvjs_Ii,"1");gvjs_vY.tf.subdir="en";gvjs_vY.tf.filename="tlz-gviz.swf";var gvjs_Oka=gvjs_kf(gvjs_lf(gvjs_vY.format,gvjs_vY.tf));gvjs_tY.prototype.wu=null;gvjs_tY.prototype.XV=null;gvjs_tY.prototype.tM=null;
var gvjs_Nka=0,gvjs_uY={};gvjs_=gvjs_tY.prototype;gvjs_.kn=!0;gvjs_.Qfa=-1;gvjs_.tO=!1;gvjs_.e3="";gvjs_.J=null;gvjs_.Hg=function(a,b,c){a=c||{};this.J=b;c=this.ga;this.kd.Kc();if(b){try{this.mN(b)}catch(e){this.kd.Zd(e.message);return}this.tO=!1;null==this.tM&&(this.tM=gvjs_Oka);var d=gvjs_mm(a,1);this.kn||d!=this.Qfa?(this.kn=!1,this.Qfa=d,this.U4(c,a),this.e3=gvjs_wY(b)):(b=gvjs_wY(b),b==this.e3?this.Ef().dataChanged():(this.Ef().metricTablesChanged(),this.e3=b))}else this.kd.Zd("Data table is null")};
function gvjs_wY(a){for(var b="",c=a.Y(),d=0;d<c;d++)b+=a.X(d)+":"+a.Xa(d)+",";return b}gvjs_.Ef=function(){return null!=this.XV?gvjs_gm().getElementById(this.XV):null};gvjs_.nua=function(a){if(null!=this.tM)throw Error("Swf url already initialzed");this.tM=a};gvjs_.getState=function(){return this.tO?gvjs_Fe(this.Ef().getState()):null};
gvjs_.mN=function(a){if(3>a.Y())throw Error("There should be at least three columns in the data.");var b;if(!(b=a.X(0)!=gvjs_f)){b=a.X(1);var c=!1,d=a.getValue(0,1);switch(b){case gvjs_e:c=0<=d&&Math.floor(d)==d;break;case gvjs_f:c=/^[0-9]{4}Q[1-4]{1}$/.test(d)||/^[0-9]{4}W[0-9]{2}$/.test(d)||/^[0-9]{4}-((0[1-9])|(1[0-2]))$/.test(d);break;case gvjs_Xa:case gvjs_Ya:c=!0}b=!c}if(b)throw Error("First and second columns must be entity and time.");for(var c=b=0,d=a.Y(),e=2;e<d;e++){if(a.X(e)!=gvjs_e&&
a.X(e)!=gvjs_f)throw Error("All data columns must be string or numbers.");a.X(e)==gvjs_e?b++:c++}if(1>b)throw Error("There must be at least one numeric column.");};
gvjs_.U4=function(a,b){var c=this.tM.replace("/en/","/"+this.tva+"/"),d=parseInt(b.width,10)||500,e=parseInt(b.height,10)||300,f=b.state,f=gvjs_m(f)?f:"",f=gvjs_we(decodeURIComponent(f))?encodeURIComponent(f):"",f={state:f,chartId:this.wu||"",js:"blocking"},g={id:this.XV};gvjs_xY("showSelectList","opt_.featureConfig_selectListComponent",b,f);gvjs_xY("showSidePanel","opt_.featureConfig_sidePanel",b,f);gvjs_xY("showXMetricPicker","opt_.featureConfig_xMetricPicker",b,f);gvjs_xY("showYMetricPicker","opt_.featureConfig_yMetricPicker",
b,f);gvjs_xY("showXScalePicker","opt_.featureConfig_xScalePicker",b,f);gvjs_xY("showYScalePicker","opt_.featureConfig_yScalePicker",b,f);gvjs_xY("showHeader","opt_.featureConfig_chartHeader",b,f);gvjs_xY(gvjs_jx,"opt_.featureConfig_chartButtons",b,f);gvjs_xY("showAdvancedPanel","opt_.featureConfig_advancedPanel",b,f);gvjs_xY("showSliderTimeDisplay","opt_.featureConfig_sliderTimeDisplay",b,f);gvjs_mg(a);b=gvjs_1f(a).createElement(gvjs_Za);var h=a.id+"_flashElement";b.id=h;a.appendChild(b);new gvjs_5R.Faa(c,
h,d,e,"9.0.0",!1,f,{scale:gvjs__t,allowScriptAccess:"always",wmode:"opaque",bgcolor:gvjs_Sq},g)};function gvjs_yY(a){gvjs_zY(a);a=gvjs_uY[a];for(var b=[{name:a.J.Xa(0),id:"dim0"}],c=[],d=a.J.Y(),e=2;e<d;e++)c.push({id:e,name:a.J.Xa(e),type:a.J.X(e)==gvjs_e?"continuous":"discrete",hasTime:!0});return gvjs_Fe({dimensions:b,metrics:c})}
function gvjs_AY(a,b){gvjs_zY(a);a=gvjs_uY[a];var c=a.J.X(1),d=[],e=[],f=[];f.push(d);f.push(e);for(var g=new gvjs_y(2,a.J.Y()-1),h=0;h<b.length;h++){if(!gvjs_Ve(g,Number(b[h])))throw Error("Column index out of range: "+b[h]);f.push([])}for(var g=a.J.fa(),k=0;k<g;k++)for(h=(a.J.Qa(k,0)+"").replace(/[\\"']/g,""),d.push(h),e.push(gvjs_Pka(a.J.getValue(k,1),c)),h=0;h<b.length;h++)f[h+2].push(a.J.getValue(k,Number(b[h])));return gvjs_Fe(f)}
function gvjs_BY(a){gvjs_zY(a);a=gvjs_uY[a];gvjs_X(a,gvjs_ui,null);a.tO||(a.tO=!0,gvjs_X(a,gvjs_L,null))}function gvjs_zY(a){if(null==gvjs_uY[a])throw Error("No chart with id "+a+" exists");}
function gvjs_Pka(a,b){if(b==gvjs_e)a=String(a);else if(b==gvjs_f&&(-1<a.indexOf("Q")||-1<a.indexOf("W")||4==a.indexOf("-")))a=String(a);else if(b==gvjs_Xa||b==gvjs_Ya){b=[];b.push(String(a.getFullYear()));var c=String(a.getMonth()+1);1==c.length&&(c="0"+c);b.push(c);a=String(a.getDate());1==a.length&&(a="0"+a);b.push(a);a=b.join("-")}else a=null;return a}function gvjs_xY(a,b,c,d){a=c[a];null!=a&&(d[b]=!!a)};gvjs_j(gvjs_$i,gvjs_tY,void 0);gvjs_tY.prototype.draw=gvjs_tY.prototype.draw;gvjs_tY.prototype.getState=gvjs_tY.prototype.getState;gvjs_tY.prototype.getChart=gvjs_tY.prototype.Ef;gvjs_tY.prototype.initSwfUrl=gvjs_tY.prototype.nua;gvjs_j("google.visualization.getMetadata",gvjs_yY,void 0);gvjs_j("google.visualization.getMetricValues",gvjs_AY,void 0);gvjs_j("google.visualization.updateExternalState",gvjs_BY,void 0);gvjs_j("getMetadata",gvjs_yY,void 0);gvjs_j("getMetricValues",gvjs_AY,void 0);
gvjs_j("updateExternalState",gvjs_BY,void 0);
