function gvjs_fY(a){gvjs_rp.call(this,a);this.eC=null;this.kd=new gvjs_np(this,this.ga);this.wua=gvjs_gY.push(this)-1;this.Sq=new gvjs_Bo}gvjs_q(gvjs_fY,gvjs_rp);var gvjs_hY=0,gvjs_gY=[];gvjs_=gvjs_fY.prototype;gvjs_.vc=null;gvjs_.m=null;gvjs_.J=null;gvjs_.ot=null;gvjs_.lR=null;gvjs_.zr=-1;gvjs_.nF=-1;gvjs_.Mi=null;
var gvjs_iY=gvjs_NM("flash","geomap","3"),gvjs_jY=gvjs_NM("base","geomap","10"),gvjs_kY={REGIONS:0,MARKERS:1},gvjs_lY=["AD","AE","AG","AI","AN","AO","AS","AW","AZ","BB","BF","BH","BI","BJ","BM","BN","BS","BV","BW","CC","CD","CF","CG","CI","CK","CL","CM","CS","CU","CV","CX","DJ","DK","DM","DO","EE","EG","EH","ER","ET","FJ","FK","FM","FO","GA","GD","GE","GF","GG","GH","GI","GL","GM","GP","GQ","GS","GU","GW","HK","HM","HR","HT","IE","IL","IM","IO","IS","JE","JO","KM","KP","KW","KY","KZ","LA","LB","LC",
"LI","LK","LR","LS","LT","LV","LY","MA","MC","MD","MG","MH","MK","ML","MN","MO","MP","MQ","MR","MS","MT","MU","MW","MZ","NA","NC","NE","NF","NG","NO","NR","NU","OM","PF","PH","PM","PN","PR","PW","QA","QM","QN","RE","RO","RU","RW","SB","SC","SD","SE","SG","SH","SI","SJ","SL","SM","SN","SO","ST","SY","SZ","TC",gvjs_Ga,"TF","TG","TJ","TK","TL","TN","TO","TT","TV","TW","UM","VA","VC","VG","VI","VN","VU","WF","WS","YE","YT","ZM","ZW",gvjs_sy,"005","013","021","002","017","009","053","054","015","018",
"030","034","035","143","145","151","154","155","039","057","061","029","011","014","150"],gvjs_Mka=["us_metro"];gvjs_=gvjs_fY.prototype;gvjs_.setSelection=function(a){this.vc.setSelection(a)};gvjs_.getSelection=function(){return this.vc.getSelection()};
gvjs_.Hg=function(a,b,c){a=c||{};this.Sq.cancel();this.vc=new gvjs_Ep;this.kd.Kc();if(this.J=b)if(this.m=a,this.m.dataMode=a.dataMode||gvjs_zi,this.m.region=a.region||gvjs_sy,this.m.resolution=a.resolution||"",this.m.width=a.width||"556px",this.m.height=a.height||"347px",this.m.colors=a.colors||[14745556,10874723,5286400,2519316],this.m.showLegend=null==a.showLegend?!0:!!a.showLegend,this.m.showZoomOut=!!a.showZoomOut,this.m.zoomOutLabel=a.zoomOutLabel||"Zoom Out",gvjs_Nb(this.m.width)&&(this.m.width+=
gvjs_M),gvjs_Nb(this.m.height)&&(this.m.height+=gvjs_M),this.m.dataMode=this.m.dataMode.toUpperCase(),c=gvjs_kY[this.m.dataMode],null!=c){this.m.dataMode=c;this.m.useSvg=!!a.useSvg;try{var d=b.Y();if(0==d)throw Error(gvjs_Fr);if(4<d)throw Error("At most four data columns can be used.");a=[];a.push(b.X(0));if(1==d){if(a[0]!=gvjs_f)throw Error("Single column must be text.");}else{a.push(b.X(1));if(a[0]!=gvjs_e&&a[0]!=gvjs_f)throw Error("First column must be text or numbers.");if(a[1]!=gvjs_e&&a[1]!=
gvjs_f)throw Error("Second column must be text or numbers.");if(3<=d)if(a.push(b.X(2)),a[0]==gvjs_e&&a[1]==gvjs_e){if(a[2]!=gvjs_e)throw Error("Third column must be a numeric value.");}else if(a[2]!=gvjs_f)throw Error("Third column must be text.");if(4==d&&(a.push(b.X(3)),a[3]!=gvjs_f))throw Error("Forth column must be text.");}}catch(e){this.kd.Zd(gvjs_Yr);return}this.J.X(0)==gvjs_f?(this.lR=!1,this.zr=1,this.nF=2):(this.lR=!0,this.zr=2,this.nF=3);b=this.J.Y()-1;b<this.zr&&(this.zr=-1);b<this.nF&&
(this.nF=-1);this.m.dataMode!=gvjs_kY.MARKERS&&this.lR?this.kd.Zd("DataMode must be set to Markers when using lat/long addresses."):(this.Mi=Math.min(this.J.fa(),400),this.J.fa()>this.Mi&&this.kd.Zd("Some of the data rows were truncated."),this.m.dataMode==gvjs_kY.MARKERS?this.lR?this.wZ():this.vZ():gvjs_hc(gvjs_Mka,this.m.region)?this.uZ():this.xZ())}else this.kd.Zd("Unsupported dataMode: "+this.m.dataMode);else this.kd.Zd(gvjs_Gr)};
gvjs_.uZ=function(){for(var a=[],b=this.J,c=0;c<this.Mi;c++){var d={},e=gvjs_1b(b.getValue(c,0));d.lat=null;d.lng=null;d.name=e;d.code=e.toUpperCase();a.push(d)}this.ot=a;gvjs_ln(this.nE,0,this)};gvjs_.wZ=function(){for(var a=[],b=this.J,c=0;c<this.Mi;c++){var d={},e=b.getValue(c,0),f=b.getValue(c,1);null==e||null==f?a.push(null):(d.lat=gvjs_1b(e),d.lng=gvjs_1b(f),d.name=d.lat+gvjs_ha+d.lng,d.code=null,a.push(d))}this.ot=a;gvjs_ln(this.nE,0,this)};
gvjs_.vZ=function(){var a=[],b=this.J,c="";2==this.m.region.length&&(c=this.m.region,c=c.toUpperCase(),c=c.replace(/GB/,"UK"),c=c.replace(/RU/,"SU"),c=c.replace(/TP/,"TL"));for(var d=0;d<this.Mi;d++){var e=gvjs_1b(b.getValue(d,0));gvjs_Mb(c)||(e+=" "+c);a.push({address:e,region:c})}0==a.length?(this.ot=[],this.nE()):this.Sq.create(a,gvjs_p(this.Y0,this))};
gvjs_.Y0=function(a){for(var b=[],c=!0,d=a.length,e=0;e<d;e++){var f=this.J.getValue(e,0);a[e]&&a[e][0]?(c=a[e][0],b.push({name:f,lat:c.geometry.location.lat(),lng:c.geometry.location.lng()}),c=!1):b.push(null)}this.ot=b;this.nE();c&&0<d&&gvjs_qp(this.kd,gvjs_Kr)};gvjs_.xZ=function(){var a=this.m.region,a=gvjs_hc(gvjs_lY,a)?"countries_en":a;0==this.Mi?(this.ot=[],this.nE()):gvjs_QM(a,gvjs_p(function(a){for(var b=[],d=0;d<this.Mi;++d)b.push(this.J.getValue(d,0));this.ot=this.bZ(b,a);this.nE()},this))};
gvjs_.bZ=function(a,b){return gvjs_s(a,function(a){var c=gvjs_Pb(gvjs_1b(a)).toLowerCase(),e=b&&gvjs_SM(b,c);return{name:a,lat:null,lng:null,code:e?e:2==c.length||"-"==c.charAt(2)?c.toUpperCase():null}},this)};
gvjs_.nE=function(){var a,b,c={};a=this.J;var d=Number(this.zr);if(-1==d)b=a=0;else{var e=Number(a.getValue(0,d));b=Number(a.getValue(0,d));for(var f=0;f<this.Mi;f++){var g=Number(a.getValue(f,d)),e=Math.max(e,g);b=Math.min(b,g)}a=e}c.Minimums=[[b,b]];c.Maximums=[[a,a]];c.TargetId=this.m.region;""==this.m.resolution?gvjs_hc(gvjs_lY,c.TargetId)?c.ZoomLevel=gvjs_Ar:c.ZoomLevel=this.m.dataMode==gvjs_kY.REGIONS?"PROVINCES":gvjs_Ar:c.ZoomLevel=this.m.resolution;c.PrimarySegmentKey=this.m.dataMode==gvjs_kY.REGIONS?
c.ZoomLevel==gvjs_Ar?"COUNTRY":"REGION":"CITY";b="Value";-1!=this.zr&&(b=this.J.Xa(this.zr));c.DataLabels=gvjs_Mb(gvjs_1b(b))?c.DataLabels=["Value","Value"]:c.DataLabels=[b,b];c.ZoomOutEnabled=this.m.showZoomOut;c.ZoomOutMessage=this.m.zoomOutLabel;c.ParentId="zoomout";c.DataIndex=0;c.Id="google.visualization.GeoMap-"+this.wua;c.CityColors=this.m.colors;c.RegionColors=this.m.colors;c.LegendEnabled=this.m.showLegend;b=[];for(a=0;a<this.Mi;a++)if(d=0,e="",-1!=this.zr&&(d=this.J.getValue(a,this.zr),
e=this.J.Qa(a,this.zr)),f=this.ot[a])g={},g.Values=[[Number(d),e]],g.ColorKey=Number(d),g.Id=this.m.dataMode==gvjs_kY.MARKERS?a:f.code,g.Lat=f.lat,g.Lng=f.lng,-1!=this.nF?g.Name=this.J.getValue(a,this.nF):f.name&&(g.Name=f.name),g.Name=g.Name?g.Name.replace(/'/g," "):g.Name,b.push(g);c.Regions=b;this.m.useSvg||(b=gvjs_Fe({GeoMap:c}),gvjs_iY.tf.filename="geomap.swf",c=gvjs_kf(gvjs_lf(gvjs_iY.format,gvjs_iY.tf)),this.eC||(this.eC=gvjs_ig(gvjs_Za),this.eC.id="google-visualization-geomap-"+gvjs_hY.toString(),
gvjs_hY+=1,gvjs_mg(this.ga),this.ga.appendChild(this.eC)),a=this.eC.id.split("-"),a=a[a.length-1],d=parseInt(this.m.width,10),e=parseInt(this.m.height,10),b={staticFilePath:gvjs_kf(gvjs_lf(gvjs_jY.format,gvjs_jY.tf)),locale:"i18n",input:encodeURIComponent(String(b))},new gvjs_5R.Faa(c,this.eC.id,d,e,"9.0.0",!1,b,{menuc:gvjs__a,wmode:"opaque",allowScriptAccess:"always",bgcolor:gvjs_Sq},{id:"google-visualization-geomap-embed-"+a}));gvjs_X(this,"drawingDone",{});gvjs_X(this,gvjs_L,null)};gvjs_.cc=function(){this.Sq.cancel()};
var gvjs_mY=gvjs_gm();gvjs_mY.onmouseup||(gvjs_mY.onmouseup=function(){});gvjs_j(gvjs_mj,gvjs_fY,void 0);gvjs_fY.prototype.draw=gvjs_fY.prototype.draw;gvjs_fY.prototype.setSelection=gvjs_fY.prototype.setSelection;gvjs_fY.prototype.getSelection=gvjs_fY.prototype.getSelection;
gvjs_j("VisualizationModule.changeGeoMap",function(a,b,c,d){d=d.slice(28);b=gvjs_gY[Number(d)];if("zoomout"==a)gvjs_X(b,"zoomOut",{});else if(gvjs_X(b,"regionClick",{region:a}),b.m.dataMode==gvjs_kY.REGIONS){c=-1;for(d=0;d<b.Mi;d++)if(b.ot[d]&&b.ot[d].code==a){c=d;break}-1!=c&&(a=gvjs_Ip(b.vc,c)?null:[{row:c}],b.setSelection(a),gvjs_X(b,gvjs_J,{}))}},void 0);
